imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "homepage-sa"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  cloudflare:
    enabled: false
    className: "cloudflare-tunnel"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    hosts:
      - host: cfv3.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: cfv3-homepage-tls
        hosts:
          - cfv3.org

  internal:
    enabled: false
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    hosts:
      - host: cfv3.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: cfv3-homepage-tls
        hosts:
          - cfv3.org

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


nodeSelector: {}
tolerations: []
affinity: {}
