name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches: [ "cloudflare_deploy_page" ]

concurrency:
  group: homepage-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BUILD_DIR: dist

jobs:
  build:
    name: Build artifact (src/)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "src/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          CI: "true"
        run: npm run build

      - name: Add _redirects (SPA fallback)
        run: |
          if [ ! -f "${BUILD_DIR}/_redirects" ]; then
            echo "/* /index.html 200" > "${BUILD_DIR}/_redirects"
          fi

      - name: Verify build dir
        run: |
          echo "Using BUILD_DIR=${BUILD_DIR}"
          test -d "${BUILD_DIR}" && ls -la "${BUILD_DIR}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: src/dist
          if-no-files-found: error
          retention-days: 1

  # deploy:
  #   name: Deploy to Cloudflare Pages
  #   runs-on: ubuntu-latest
  #   needs: build
  #   env:
  #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #     CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #     PAGES_PROJECT_NAME: ${{ secrets.PAGES_PROJECT_NAME }}
  #   steps
