name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches: [ "main" ]

concurrency:
  group: homepage-cloudflared-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "app/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          CI: "true"
        run: npm run build

      - name: Add _redirects (SPA fallback)
        run: |
          if [ ! -f "dist/_redirects" ]; then
            echo "/* /index.html 200" > "dist/_redirects"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: app/dist
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist-for-deploy

      - name: Install Wrangler
        run: npm i -g wrangler@latest

      - name: Deploy (production)
        run: |
          wrangler pages deploy dist-for-deploy \
            --project-name homepage \
            --branch main
